config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "index#show"

  # Registro
  get "/usuarios" => "usuarios#new"

  # Muro y Perfil
  get "/mi_inicio" => "usuarios#muro", as: "muro"
  get "/mi_perfil" => "usuarios#perfil", as: "mi_perfil"

  # Login/Logout
  get "/login" => "sesiones#new", as: "login"
  post "/login" => "sesiones#create", as: "iniciar_sesion"
  delete "/logout" => "sesiones#destroy", as: "logout"
  get "/registro" => "usuarios#new", as: "registro"

  resources :usuarios, except: [ :index ] do
  	resources :posts, only: [ :new, :create, :show, :destroy ] do
      resources :comentarios, only: [ :new, :create, :destroy ]
  	end
  end
end

app/models/amigo.rb
class Amigo < ApplicationRecord
  belongs_to :usuario
  belongs_to :amistad, class_name: "Usuario"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :usuario
  belongs_to :post

  validates :contenido, presence: { message: "no puede estar vacio" }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :usuario
  
  has_many :comentarios, dependent: :destroy

  validates :contenido, presence: { message: "no puede estar vacio" }
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password

  has_many :amigos, dependent: :destroy
  has_many :amistades, through: :amigos
  has_many :posts, dependent: :destroy
  has_many :comentarios, dependent: :destroy

  validates :correo, uniqueness: { message: "ya existe" }

  validates :nombre, :apellido, presence: { message: "no puede estar vacio" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :buscar_usuario, :iniciar_sesion, :cargar_personas

  protected
    def buscar_usuario
      if session[:usuario_id]
        @usuario_actual = Usuario.find session[:usuario_id]
      else
      	@usuario_actual = nil
      end
    end

    def iniciar_sesion
      unless session[:usuario_id]
      	redirect_to login_path, notice: "Inicia sesion primero!"
      end
    end

    def cargar_personas
      @personas = Usuario.all
    end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController

  def create
    @post = Post.find params[:post_id]
    @comentario = @post.comentarios.new

    @comentario.contenido = params[:comentario][:contenido]
    @comentario.usuario_id = @usuario_actual.id

    if @comentario.save
      redirect_back fallback_location: muro_path, notice: "Has comentado!"
    else
      redirect_back fallback_location: muro_path, notice: "No se ha podido publicar tu comentario :("
    end
  end

  def destroy
    @comentario = Comentario.find params[:id]
    @comentario.destroy
    redirect_back fallback_location: muro_path, notice: "Borrado con exito!"
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  skip_before_action :iniciar_sesion
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find_by id: params[:id]

    unless @post
      redirect_to muro_path, notice: "Se borro con exito!"
    end
  end

  def create
    @usuario_actual.posts.create! contenido: params[:post][:contenido]
    redirect_back fallback_location: muro_path, notice: "Tu publicacion se creó con exito"
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_back fallback_location: root_path, notice: "Borrado con exito!"
  end
end

app/controllers/sesiones_controller.rb
class SesionesController < ApplicationController
  skip_before_action :iniciar_sesion

  def create
  	@usuario = Usuario.find_by correo: params[:correo]
  	@contra = params[:password]

  	if @usuario && @usuario.authenticate(@contra)
  	  session[:usuario_id] = @usuario.id
  	  redirect_to muro_path, notice: "Iniciaste sesion correctamente"
  	else
  	  render 'new'
  	end
  end

  def destroy
  	reset_session
  	redirect_to root_path, notice: "Cerraste sesion con exito"
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  skip_before_action :iniciar_sesion, only: [ :new, :create ]

  def perfil
  	@posts = @usuario_actual.posts
  end

  def muro
  	@posts = Post.all
  end

  def amigos
  end

  def new
    @usuario = Usuario.new
  end

  def create
  	@usuario = Usuario.new parametros_de_usuario

  	if @usuario.save
  	  session[:usuario_id] = @usuario.id
  	  redirect_to muro_path, notice: "Has creado tu cuenta con exito"
  	else
  	  render 'new'
  	end

  end

  def edit
  end

  def destroy
  end

  private
    def parametros_de_usuario
      params.
        require(:usuario).
          permit( :nombre,
          		  :apellido,
          		  :correo,
          		  :password )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sesiones_helper.rb
module SesionesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/comentarios/_comentario.html.erb
<div class="comentario" style="background-color:gray; padding:5px; border:1px solid black; margin-left:5px; border-radius:5px; margin-top: 10px; margin-bottom: 10px; width:300px;">
  <p><%= comentario.usuario.nombre %> dice: </p>
  <p><%= comentario.contenido %></p>
  <% if comentario.usuario.id == @usuario_actual.id %>
    <%= link_to "Borrar", usuario_post_comentario_path(@usuario_actual, @post, comentario), method: :delete %>
  <% end %>
</div>

app/views/comentarios/_form.html.erb
<%= form_with model: [@usuario_actual, @post, Comentario.new], local: true do |f| %>

  <div class="field">
  	<%= f.label "Di lo que tengas que decir" %> <br>
  	<%= f.text_area :contenido %>
  </div>

  <div class="submit">
  	<%= f.submit "Comentar" %>
  </div>

<% end %>

app/views/index/show.html.erb
<h1>Bienvenido a NotFacebook</h1>
<p>Inicia sesion o create una cuenta!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotFacebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="app-cabecera">
      <h1><%= link_to "NotFacebook!", root_path %></h1>
      <% unless session[:usuario_id] %>
        <%= link_to "Iniciar Sesion", login_path %> | 
        <%= link_to "Registrate!", registro_path %>
      <% else %>
        <%= @usuario_actual.nombre + " " + @usuario_actual.apellido %> | 
        <%= link_to "Mi Perfil", mi_perfil_path %> | 
        <%= link_to "Mi Inicio", muro_path %> | 
        <%= link_to "Cerrar Sesion", logout_path, method: :delete %>
    <% end %>
    </div>

    <% if session[:usuario_id] %>
      <div class="app-usuarios" style="height:100px; overflow: auto; border:1px solid black; margin: 10px; width: 500px; padding-top:5px; padding-left: 15px;">
        <p>Personas que tal vez conozcas (o tal vez no)</p>
        <ul>
          <% @personas.each do |p| %>
            <li><%= p.nombre + " " + p.apellido + ", posts: #{p.posts.count}, comentarios: #{p.comentarios.count}" %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="app-notificaciones" style="margin-top:15px; color: #89D800;">
      <%= notice %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: [@usuario_actual, Post.new], local: true do |f| %>

  <div class="field">
  	<%= f.label "Dinos que piensas!" %> <br>
  	<%= f.text_area :contenido %>
  </div>

  <div class="submit">
  	<%= f.submit %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div class="post" style="background-color:gray; padding:5px; border:1px solid black; margin-left:5px; border-radius:5px; margin-top: 10px; margin-bottom: 10px; width:300px;">
  <h4><%= post.usuario.nombre + " " + post.usuario.apellido %> dice: </h4>
  <p><%= post.contenido %></p>

  <p>
    Comentarios: <%= post.comentarios.count %>
  </p>

  <p>
  	<%= link_to "Ver Publicacion (puedes comentar)", usuario_post_path(post.usuario, post) %>
  </p>
  
  <p>
  	<% if post.usuario == @usuario_actual %>
      <%= link_to "Borrar publicacion", usuario_post_path(@usuario_actual, post), method: :delete %>
  	<% end %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/show.html.erb
<%= render @post %>

<h4>Comentarios!</h4>
<p>Crea uno!</p>

<%= render 'comentarios/form' %>

<%= render @post.comentarios %>

app/views/sesiones/_form.html.erb
<%= form_with url: iniciar_sesion_path, local: true do |f| %>
  <div class="field">
  	<%= f.label :correo %> <br>
    <%= f.text_field :correo %>
  </div>

  <div class="field">
  	<%= f.label "Contraseña" %> <br>
  	<%= f.password_field :password %>
  </div>

  <div class="inicar-sesion-submit">
  	<%= f.submit "iniciar sesion" %>
  </div>
<% end %>

app/views/sesiones/new.html.erb
<h2>Inicia Sesion</h2>

<%= render 'form' %>

app/views/usuarios/_form.html.erb
<%= form_with model: @usuario, local: true do |f| %>

  <% if @usuario.errors.any? %>
  
    <div class="errores-usuario">
      <%= pluralize( @usuario.errors.count, "error" ) %>, revisa los campos
    </div>

    <ul>
      <% @usuario.errors.full_messages.each do |mensaje| %>
        <li><%= mensaje %></li>
      <% end %>
    </ul>

  <% end %>

  <div class="field">
    <%= f.label :nombre %> <br> 
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
  	<%= f.label :apellido %> <br>
    <%= f.text_field :apellido %>
  </div>

  <div class="field">
  	<%= f.label :correo %> <br>
    <%= f.text_field :correo %>
  </div>
  
  <div class="field">
  	<%= f.label "Contraseña" %> <br>
    <%= f.password_field :password %>
  </div>

  <div class="submit">
  	<%= f.submit "Registrarme" %>
  </div>

<% end %>

app/views/usuarios/amigos.html.erb
<h1>Usuarios#amigos</h1>
<p>Find me in app/views/usuarios/amigos.html.erb</p>

app/views/usuarios/muro.html.erb
<h2>Mi inicio</h2>
<p>Ve qué publican tus amigos, desconocidos o publica algo</p>

<h3>Crea un post!</h3>

<%= render 'posts/form' %>

<%= render @posts %>

app/views/usuarios/new.html.erb
<h2>Registro</h2>

<%= render 'form' %>

app/views/usuarios/perfil.html.erb
<h2>Mi perfil!</h2>
<div class="perfil-nombre">
  <h3><%= @usuario_actual.nombre + " " + @usuario_actual.apellido %></h3> <br>
  Amigos: <%= @usuario_actual.amigos.count %> (aun no se implementa, ajio)
</div>

<div class="perfil-post">
  <%= render 'posts/form' %>
</div>


<h4>Mis publicaciones!</h4>

<div class="perfil-publicaciones">
	<%= render @posts %>
</div>